image: quickcorp/qcobjects:latest

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
  - npm i qcobjects && npm i -D eslint-config-qcobjects
  - npm ci
  - npm test
  - mkdir public
  - npm run publish:web
  - cp src/_redirects public/
  - cp -r node_modules/qcobjects-sdk public/qcobjects-sdk
  # Build the public/ directory first
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
    - node_modules/qcobjects-sdk
    - build
    - public
  only:
  - main
